/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Ssrp-Website\public\earthtrial.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EarthModel(props) {
  const { nodes, materials } = useGLTF('./models/earthtrial.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials.Material} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.001']} scale={1.017} />
    </group>
  )
}

useGLTF.preload('./models/earthtrial.glb')
